import type { CaseStudyData } from './nexspot'

export const psychicozMobCaseStudy: CaseStudyData = {
  id: 'psychicoz-mob',
  title: 'PsychicOz Mobile Application',
  summary: 'Comprehensive cross-platform mobile application built with React Native that connects users with psychic readers for various types of spiritual consultations.',
  tags: ['React Native', 'TypeScript', 'Pusher', 'Twilio', 'OpenTok', 'Real-time Communication', 'Mobile App'],
  liveUrl: 'https://psychicoz.com/',
  pdfUrl: '/case-studies/psychicoz-mob.pdf',
  hero: {
    title: 'PsychicOz Mobile Application',
    summary: 'A comprehensive cross-platform mobile application built with React Native 0.76.3 that connects users with psychic readers for various types of spiritual consultations. The application provides real-time communication capabilities including phone calls, live chat, and email readings, along with a complete user management and payment system. Features include deep linking, real-time messaging via Pusher, video/voice calling through Twilio OpenTok, comprehensive psychic discovery, and secure payment processing.',
    tags: ['React Native 0.76.3', 'TypeScript 5.0.4', 'Pusher WebSocket', 'Twilio OpenTok', 'Real-time Chat', 'Mobile App', 'Cross-platform'],
  },
  overview: {
    client: 'PsychicOz - Trusted Psychic Service Provider',
    problem: 'PsychicOz needed a comprehensive cross-platform mobile application built with React Native that connects users with psychic readers for various types of spiritual consultations. The application required real-time communication capabilities including phone calls, live chat, and email readings, along with a complete user management and payment system. Key requirements included: support for multiple communication channels (phone calls via Twilio, live chat via Pusher WebSocket, email readings), comprehensive psychic discovery with advanced filtering (by reading subjects, psychic abilities, and tools), secure payment processing with credit-based system and multiple payment methods, deep linking support for seamless web-to-app navigation, robust user authentication and profile management, offline mode handling and network resilience, and integration with multiple third-party services (Pusher, Twilio OpenTok, Sentry, Zendesk) while maintaining high performance and reliability across both iOS and Android platforms.',
    goals: [
      'Build a cross-platform mobile application using React Native 0.76.3 for iOS and Android',
      'Implement real-time communication features (phone calls, live chat, email readings)',
      'Develop comprehensive psychic discovery with advanced filtering and search',
      'Create secure payment processing with credit-based system and multiple payment methods',
      'Implement deep linking for seamless navigation from web to app',
      'Build robust user authentication and profile management',
      'Integrate real-time messaging using Pusher WebSocket',
      'Implement video and voice calling through Twilio OpenTok',
      'Create offline mode handling and network resilience',
      'Ensure high performance with optimized rendering and state management',
    ],
    stats: {
      timeline: '12+ weeks',
      stack: ['React Native 0.76.3', 'React 18.3.1', 'TypeScript 5.0.4', 'React Navigation 7.x', 'Pusher WebSocket 1.3.1', 'Twilio OpenTok 2.29.1', 'AsyncStorage 2.1.0', 'Sentry 6.3.0', 'Zendesk 0.3.2', 'FlashList 1.8.3'],
      role: 'Full-Stack Mobile Developer',
      outcomes: [
        'Successfully launched comprehensive cross-platform mobile application for iOS and Android',
        'Real-time communication features (phone, chat, email) significantly improved user engagement',
        'Advanced filtering and search capabilities increased successful psychic-customer matches',
        'Deep linking integration enabled seamless navigation from web to app',
        'Comprehensive error monitoring with Sentry provided valuable insights for continuous improvement',
        'Network resilience features ensured smooth user experience even with intermittent connectivity',
        'High-performance rendering with FlashList handled large datasets (48+ screens, 26+ components) efficiently',
        'Application successfully handles complex state management and real-time updates',
      ],
    },
  },
  gallery: [
    {
      src: '/images/Simulator Screenshot - iPhone 17 Pro - 2025-12-18 at 14.31.38.png',
      alt: 'PsychicOz mobile app screen 1',
      caption: 'Mobile app interface showcasing crop feature',
      tag: 'Mobile App',
    },
    {
      src: '/images/Simulator Screenshot - iPhone 17 Pro - 2025-12-18 at 14.33.55.png',
      alt: 'PsychicOz mobile app screen 2',
      caption: 'Top rated psychics',
      tag: 'Mobile App',
    },
    {
      src: '/images/Simulator Screenshot - iPhone 17 Pro - 2025-12-18 at 14.34.16.png',
      alt: 'PsychicOz mobile app screen 3',
      caption: 'Payment and account management features',
      tag: 'Mobile App',
    },
    {
      src: '/images/Simulator Screenshot - iPhone 17 Pro - 2025-12-18 at 14.34.34.png',
      alt: 'PsychicOz mobile app screen 4',
      caption: 'Purchase History',
      tag: 'Mobile App',
    },
    {
      src: '/images/Simulator Screenshot - iPhone 17 Pro - 2025-12-18 at 14.34.50.png',
      alt: 'PsychicOz mobile app screen 5',
      caption: 'Email reading system',
      tag: 'Mobile App',
    },
  ],
  process: [
    {
      title: 'Requirements & Architecture Design',
      description: 'Analyzed PsychicOz\'s business requirements and existing web platform functionality. Designed a scalable React Native architecture with TypeScript for type safety. Planned multi-channel communication system, real-time messaging infrastructure, deep linking architecture, and payment integration strategy. Identified key technical challenges including WebSocket connection management, call state handling, offline mode, and cross-platform consistency. Structured the application with 48+ screen components, 26+ reusable components, and comprehensive utility functions.',
    },
    {
      title: 'Technology Stack Selection',
      description: 'Selected React Native 0.76.3 (latest stable version) as the core framework with React 18.3.1 and TypeScript 5.0.4 for type safety. Implemented React Navigation 7.x (@react-navigation/native 7.0.12, native-stack 7.1.13, drawer 7.0.17) for complex navigation flows with deep linking support. Integrated Pusher WebSocket (@pusher/pusher-websocket-react-native 1.3.1) for real-time messaging and notifications. Selected Twilio OpenTok (opentok-react-native 2.29.1) for video and voice calling capabilities. Implemented AsyncStorage (@react-native-async-storage/async-storage 2.1.0) for local data persistence, Sentry (@sentry/react-native 6.3.0) for error monitoring, FlashList (@shopify/flash-list 1.8.3) for high-performance list rendering, and React Hook Form (7.53.2) for form handling.',
    },
    {
      title: 'Real-time Communication System',
      description: 'Built comprehensive real-time communication system using Pusher WebSocket for live chat with typing indicators, message synchronization (text, emoji, images), online/offline status tracking, and persistent chat transcripts. Integrated Twilio OpenTok for video and voice calling with token generation and management, call state handling, duration tracking, call history, and Android foreground service support. Implemented email reading system with dedicated inbox interface, email composition, conversation-style threading, and deep linking support. Created PusherContext for WebSocket connection management with automatic reconnection logic, event queuing during disconnections, and channel subscription/unsubscription.',
    },
    {
      title: 'Psychic Discovery & Filtering',
      description: 'Developed sophisticated psychic discovery system with advanced filtering by reading subjects (Love & Relationships, Career, Life Path, Money, Pets, Past Life, Deceased Loved Ones, Missing Persons), psychic abilities (Medium, Clairvoyant, Clairaudient, Empath), and tools (Tarot, Astrology, Numerology, Crystals). Implemented real-time search with debouncing, customer favorites, staff picks, and rising stars features. Created comprehensive psychic profile pages with ratings, reviews, availability status, sample readings, gallery, and communication options.',
    },
    {
      title: 'Deep Linking & Navigation',
      description: 'Implemented comprehensive deep linking system supporting multiple URL patterns: /app_verification_success.php?id={id} for email verification, /mail/{mode}/{mailId}/{type} for email readings, /conversation/{psychicUsername} for chat conversations, and /userdashbord.php?readmail_id={id}&mail_type={type} for dashboard navigation. Created safe navigation wrapper with retry logic and authentication-aware routing. Built RouteContext for route state management with complex navigation flows including drawer and stack navigators. Implemented URL parsing, parameter extraction, navigation state management, and fallback to web browser for unsupported links.',
    },
    {
      title: 'Payment & Billing System',
      description: 'Integrated secure payment processing with credit-based system supporting multiple payment methods including credit/debit cards (with card-validator 10.0.0) and cryptocurrency payments. Implemented account balance management, transaction history, and purchase flow. Created special checkout flow for introductory offers. Integrated JWT authentication (react-native-pure-jwt 3.0.2) and secure payment gateway communication with PCI-compliant processing.',
    },
    {
      title: 'State Management & Performance',
      description: 'Implemented Context API for global state management (AuthContext, PusherContext, RouteContext). Used React Hooks extensively (useState, useEffect, useRef, useCallback) for component state and side effects. Implemented FlashList for high-performance list rendering of large datasets with virtual scrolling. Applied memoization with React.memo and useMemo for component optimization. Implemented lazy loading, code splitting, and image optimization for improved performance.',
    },
    {
      title: 'Error Handling & Network Resilience',
      description: 'Integrated Sentry for comprehensive error tracking with intelligent error filtering: network errors (filtered as non-critical), authentication errors (handled gracefully), navigation errors (recoverable), and user-initiated cancellations. Implemented network state monitoring using @react-native-community/netinfo (11.4.1) with automatic retry mechanisms, offline mode handling, connection restoration events, and API reload on reconnection. Created user-friendly error messages with retry options, error enrichment with device context, and breadcrumb tracking for debugging. Ensured 24/7 availability with robust error handling and monitoring.',
    },
    {
      title: 'UI/UX Design & Platform Optimization',
      description: 'Designed intuitive mobile interface with platform-specific optimizations for iOS (native alerts, safe area handling, iOS-specific UI patterns) and Android (Material Design elements, foreground services, Android-specific navigation). Implemented custom components including CustomHeader, CustomAlert, VideoModal, progress indicators (react-native-progress 5.0.1), emoji keyboard (react-native-emoji-selector 0.2.0, rn-emoji-keyboard 1.7.0), and vector icons (react-native-vector-icons 10.2.0). Created responsive layouts with proper safe area handling, smooth animations and transitions, and accessibility features. Used FlashList for optimized list rendering, implemented memoization for performance, and ensured platform-specific UI patterns for native-like experience.',
    },
  ],
  results: {
    title: 'Results & Impact',
    bullets: [
      'Successfully launched comprehensive cross-platform mobile application (React Native 0.76.3) for iOS and Android',
      'Real-time communication system (phone via Twilio, chat via Pusher, email) significantly improved user engagement',
      'Advanced filtering and search capabilities by reading subjects, abilities, and tools increased successful matches',
      'Deep linking integration enabled seamless navigation from web to app with multiple URL pattern support',
      'Comprehensive error monitoring with Sentry (intelligent filtering) provided valuable insights for continuous improvement',
      'Network resilience features (automatic retry, offline mode, connection restoration) ensured smooth user experience',
      'High-performance rendering with FlashList handled large datasets (48+ screens, 26+ components) efficiently',
      'Secure payment processing with credit/debit cards and cryptocurrency increased conversion rates',
      'Platform-specific optimizations (iOS native alerts, Android Material Design) provided native-like experience',
      'Robust state management (Context API: AuthContext, PusherContext, RouteContext) maintained application stability',
      'Application structure includes 48+ screen components, 26+ reusable components, and comprehensive utility functions',
      'Real-time WebSocket connections with Pusher maintained stable messaging and notification delivery',
      'Twilio OpenTok integration enabled reliable video and voice calling with proper call state management',
    ],
    nextSteps: [
      'Enhanced push notification system for better user engagement',
      'Advanced search and filtering capabilities',
      'Social features including sharing and referrals',
      'Enhanced video calling features',
      'Multi-language support',
      'Dark mode implementation',
      'Enhanced accessibility features',
    ],
  },
  features: [
    'Cross-platform Mobile App - React Native 0.76.3 for iOS and Android',
    'Real-time Messaging - Pusher WebSocket integration for live chat with typing indicators',
    'Video & Voice Calling - Twilio OpenTok integration for video and voice consultations',
    'Email Readings - Comprehensive email reading system with inbox management',
    'Deep Linking - Support for multiple URL patterns and seamless web-to-app navigation',
    'Advanced Filtering - Filter psychics by reading subjects, abilities, and tools',
    'Search Functionality - Real-time search with debouncing and relevance ranking',
    'Psychic Profiles - Detailed profiles with ratings, reviews, and availability status',
    'Customer Favorites - Save and easily access favorite psychics',
    'Staff Picks & Rising Stars - Curated selections to help discover psychics',
    'Payment Integration - Secure payment processing with credit/debit cards and cryptocurrency',
    'Account Management - Credit-based system with balance management and transaction history',
    'User Authentication - Complete signup, login, phone verification, and profile management',
    'Offline Mode - Network resilience with offline handling and automatic retry',
    'Error Monitoring - Sentry integration with intelligent error filtering',
    'Network Monitoring - Real-time connectivity detection and connection restoration',
    'Navigation System - Complex navigation with drawer and stack navigators',
    'State Management - Context API for global state with AuthContext, PusherContext, RouteContext',
    'Performance Optimization - FlashList for efficient rendering, memoization, and lazy loading',
    'Platform-Specific Features - iOS and Android optimizations with native UI components',
    'Media Handling - Image picker, video player, document picker, and file system integration',
    'HTML Rendering - React Native Render HTML for rich content display',
    'Zendesk Integration - In-app customer support and help system',
  ],
}

