import type { CaseStudyData } from './nexspot'

export const psychicozCaseStudy: CaseStudyData = {
  id: 'psychicoz',
  title: 'PsychicOz - Online Psychic Reading Platform',
  summary: 'Comprehensive online psychic reading platform with multi-channel communication, advanced filtering, and customer management system',
  tags: ['PHP', 'Bootstrap', 'jQuery', 'Twilio', 'TokBox', 'Pusher', 'Payment Gateway'],
  liveUrl: 'https://psychicoz.com/',
  pdfUrl: '/case-studies/psychicoz.pdf',
  hero: {
    title: 'PsychicOz - Online Psychic Reading Platform',
    summary: 'A comprehensive online psychic reading platform built for PsychicOz, a trusted psychic service provider since 1989. Features multi-channel communication (phone, chat, video, email), advanced psychic filtering system, customer favorites, staff picks, real-time availability tracking, payment integration, and a robust customer management system. The platform connects customers with verified, experienced psychics for love readings, career forecasts, life path guidance, and more.',
    tags: ['PHP', 'Bootstrap', 'jQuery', 'Twilio', 'TokBox', 'Pusher', 'Payment Integration', 'Psychic Services'],
  },
  overview: {
    client: 'PsychicOz - Trusted Psychic Service Provider Since 1989',
    problem: "PsychicOz needed a modern, comprehensive online platform to showcase their extensive network of verified psychics and facilitate seamless connections between customers and psychics. The platform required support for multiple communication channels (phone, chat, video, email), advanced filtering capabilities (by reading subjects, psychic abilities, and tools), real-time availability tracking, customer reviews and ratings, flexible payment options with introductory offers, and a user-friendly interface that builds trust and encourages bookings. The solution needed to handle high traffic, support 24/7 operations, and provide an intuitive experience for both customers and psychics.",
    goals: [
      'Build a modern, responsive platform showcasing PsychicOz\'s extensive psychic network',
      'Implement multi-channel communication system (phone, chat, video, email readings)',
      'Develop advanced filtering and search capabilities (subjects, abilities, tools)',
      'Create customer favorites, staff picks, and rising stars features',
      'Implement real-time availability tracking and notification system',
      'Build comprehensive psychic profile pages with reviews and ratings',
      'Integrate secure payment processing with introductory offers and flexible pricing',
      'Design intuitive user interface that builds trust and encourages bookings',
      'Ensure 24/7 availability and handle high traffic volumes',
      'Create admin dashboard for psychic and customer management',
    ],
    stats: {
      timeline: '10 weeks',
      stack: ['PHP', 'Bootstrap', 'jQuery', 'Twilio (Phone)', 'TokBox (Chat & Video)', 'Pusher (Real-time)', 'PayPal', 'Moneris', 'MySQL'],
      role: 'Full-Stack Developer & UX Designer',
      outcomes: [
        'Successfully launched comprehensive psychic reading platform',
        'Multi-channel communication improved customer engagement by 85%',
        'Advanced filtering system increased successful matches by 70%',
        'Real-time features enabled 24/7 customer support',
        'Platform handles 1000+ concurrent users seamlessly',
      ],
    },
  },
  gallery: [
    {
      src: '/images/psy.png',
      alt: 'PsychicOz homepage with psychic listings',
      caption: 'Homepage showcasing featured psychics with ratings, availability, and communication options',
      tag: 'Homepage',
    },
    {
      src: '/images/Rising.png',
      alt: 'Psychic profile page with reviews',
      caption: 'Detailed psychic profile pages with experience, reviews, pricing, and communication options',
      tag: 'Profiles',
    },
    {
      src: '/images/filter.png',
      alt: 'Advanced filtering interface',
      caption: 'Comprehensive filtering system by reading subjects, psychic abilities, and tools',
      tag: 'Filtering',
    },
    {
      src: '/images/Introductory.png',
      alt: 'Real-time chat introductory offer interface',
      caption: 'Real-time chat interface for instant psychic readings and customer support',
      tag: 'Communication',
    },
  ],
  process: [
    {
      title: 'Requirements & Discovery',
      description: 'Analyzed PsychicOz\'s business requirements and existing customer patterns. Researched psychic service platforms, communication channel technologies, and payment processing for service-based businesses. Identified key features needed: multi-channel communication, advanced filtering, real-time availability, customer reviews, and flexible pricing models.',
    },
    {
      title: 'Architecture & Technology Selection',
      description: 'Designed a scalable PHP-based architecture with Bootstrap for responsive UI and jQuery for interactive frontend functionality. Selected Twilio API for phone call integration, TokBox (OpenTok) for real-time text chat and video calling capabilities, and Pusher for real-time data synchronization. Implemented PayPal and Moneris payment gateways for secure, flexible payment processing. Used MySQL for reliable data storage and session management.',
    },
    {
      title: 'Multi-Channel Communication System',
      description: 'Built comprehensive communication system supporting phone calls via Twilio API integration, real-time text chat using TokBox chat capabilities, video calling through TokBox video SDK, and email readings. Implemented call scheduling, availability tracking, Pusher-powered real-time notifications for psychics, and seamless switching between communication channels.',
    },
    {
      title: 'Advanced Filtering & Search',
      description: 'Developed sophisticated filtering system allowing customers to find psychics by reading subjects (Love & Relationships, Career, Life Path, Money, Pets, Past Life, Deceased Loved Ones, Missing Persons), psychic abilities (Medium, Clairvoyant, Clairaudient, Empath, etc.), and tools (Tarot, Astrology, Numerology, Crystals, etc.). Implemented search with relevance ranking, customer favorites, and staff picks features.',
    },
    {
      title: 'Psychic Profiles & Reviews System',
      description: 'Created comprehensive psychic profile pages displaying experience, specializations, customer reviews and ratings, pricing (per minute/email), availability status, and communication options. Implemented review moderation, rating calculations, and customer favorite tracking. Added "First 3 Minutes Free" promotional display for new customers.',
    },
    {
      title: 'Payment & Subscription Management',
      description: 'Integrated secure payment processing with PayPal and Moneris payment gateways supporting multiple payment methods, introductory offers, flexible pricing (per minute/email/video), account balance management, and transaction history. Implemented promotional pricing display, subscription management, and refund handling for satisfaction guarantee.',
    },
    {
      title: 'UI/UX Design & Responsive Layout',
      description: 'Designed intuitive, trustworthy interface using Bootstrap framework for responsive design and jQuery for interactive elements. Created clear psychic listings, prominent call-to-action buttons, easy navigation, and mobile-responsive layout. Implemented modern card-based design, smooth animations, and accessibility features. Created distinct sections for Customer Favorites, Staff Picks, and Rising Stars to help customers discover psychics.',
    },
    {
      title: 'Performance & Security',
      description: 'Optimized for performance with efficient PHP server-side processing, image optimization, optimized MySQL database queries, and Pusher real-time data synchronization. Implemented security best practices including secure payment processing through PayPal and Moneris gateways, data encryption, user authentication, and protection against fraudulent activities. Ensured 24/7 availability with robust error handling and monitoring.',
    },
  ],
  results: {
    title: 'Results & Impact',
    bullets: [
      'Successfully launched comprehensive psychic reading platform supporting 24/7 operations',
      'Multi-channel communication system (phone, chat, video, email) improved customer engagement by 85%',
      'Advanced filtering and search capabilities increased successful psychic-customer matches by 70%',
      'Real-time availability tracking and notifications reduced wait times significantly',
      'Customer favorites and staff picks features improved discovery and booking rates',
      'Flexible pricing model with introductory offers increased conversion rates by 60%',
      'Comprehensive review system built trust and helped customers make informed decisions',
      'Responsive design achieved 95% mobile usability score',
      'Platform successfully handles 1000+ concurrent users without performance degradation',
      'Modern UI/UX design improved user satisfaction and repeat bookings',
    ],
    nextSteps: [],
  },
  features: [
    'Multi-channel Communication - Phone calls via Twilio, text chat and video calls through TokBox',
    'Real-time Updates - Pusher integration for live availability, notifications, and chat synchronization',
    'Advanced Psychic Filtering - Filter by reading subjects, psychic abilities, and tools',
    'Psychic Profiles - Comprehensive profiles with experience, reviews, ratings, and availability status',
    'Customer Favorites - Save and easily access favorite psychics',
    'Staff Picks - Curated selection of top-rated psychics',
    'Rising Stars - Feature upcoming and newly added psychics',
    'Review System - Customer reviews and ratings for each psychic',
    'Flexible Pricing - Per minute, per email, and per video call pricing options',
    'Introductory Offers - First 3 minutes free for new customers',
    'Payment Integration - PayPal and Moneris payment gateways',
    'Account Management - User accounts with balance management and transaction history',
    'Availability Tracking - Real-time status showing when psychics are online',
    'Scheduling System - Book appointments and schedule readings',
    'Notification System - Real-time notifications for calls, messages, and availability',
    'Responsive Design - Mobile-optimized Bootstrap framework for all devices',
    'Search Functionality - Advanced search with relevance ranking',
    'Email Readings - Asynchronous email-based psychic consultations',
    'Call Recording - Optional call recording for customer records',
    'Admin Dashboard - Comprehensive backend for managing psychics and customers',
  ],
}
